// Generated by 05-documents/training-manual/publish.py — do not edit.
// Rebuild the manual, then run it again; the reader follows.

export const EDITION = "e2";
export const PAGE_COUNT = 64;
// Changes with every rebuild, and rides on every page and PDF address:
// the files are cached for an hour, and the addresses do not otherwise
// change, so without it a reader could see last edition's pages.
export const VERSION = "264ed0be2b";
export const PDF_URL = "/api/manual/pdf";
export const PDF_BYTES = 6233792;

export type Entry = { no: string; title: string; page: number; part: boolean };
export const CONTENTS: Entry[] = [
  {
    "no": "",
    "title": "Who does what",
    "page": 3,
    "part": false
  },
  {
    "no": "01",
    "title": "Getting started",
    "page": 4,
    "part": true
  },
  {
    "no": "1.1",
    "title": "Signing in",
    "page": 5,
    "part": false
  },
  {
    "no": "1.2",
    "title": "Check your email, and two-step sign-in",
    "page": 6,
    "part": false
  },
  {
    "no": "1.3",
    "title": "Finding your way round",
    "page": 7,
    "part": false
  },
  {
    "no": "1.4",
    "title": "Search anything (Ctrl K)",
    "page": 8,
    "part": false
  },
  {
    "no": "1.5",
    "title": "Setting up a new brokerage",
    "page": 9,
    "part": false
  },
  {
    "no": "02",
    "title": "Your working day",
    "page": 10,
    "part": true
  },
  {
    "no": "2.1",
    "title": "Today",
    "page": 11,
    "part": false
  },
  {
    "no": "2.2",
    "title": "The Inbox",
    "page": 12,
    "part": false
  },
  {
    "no": "2.3",
    "title": "A conversation, and the assistant's replies",
    "page": 13,
    "part": false
  },
  {
    "no": "2.4",
    "title": "Leads",
    "page": 14,
    "part": false
  },
  {
    "no": "2.5",
    "title": "Adding a lead",
    "page": 15,
    "part": false
  },
  {
    "no": "2.6",
    "title": "Importing and exporting leads",
    "page": 16,
    "part": false
  },
  {
    "no": "2.7",
    "title": "A person's page",
    "page": 17,
    "part": false
  },
  {
    "no": "2.8",
    "title": "Tasks and follow-ups",
    "page": 18,
    "part": false
  },
  {
    "no": "2.9",
    "title": "Adding a task",
    "page": 19,
    "part": false
  },
  {
    "no": "2.10",
    "title": "The diary and booking viewings",
    "page": 20,
    "part": false
  },
  {
    "no": "2.11",
    "title": "Say it: record by voice or text",
    "page": 21,
    "part": false
  },
  {
    "no": "2.12",
    "title": "Find anyone",
    "page": 22,
    "part": false
  },
  {
    "no": "2.13",
    "title": "Your blackbook",
    "page": 23,
    "part": false
  },
  {
    "no": "2.14",
    "title": "My figures, availability and alerts",
    "page": 24,
    "part": false
  },
  {
    "no": "03",
    "title": "Properties and deals",
    "page": 25,
    "part": true
  },
  {
    "no": "3.1",
    "title": "Listings",
    "page": 26,
    "part": false
  },
  {
    "no": "3.2",
    "title": "Adding a property",
    "page": 27,
    "part": false
  },
  {
    "no": "3.3",
    "title": "The page a buyer sees",
    "page": 28,
    "part": false
  },
  {
    "no": "3.4",
    "title": "Owners (vendors)",
    "page": 29,
    "part": false
  },
  {
    "no": "3.5",
    "title": "The pipeline",
    "page": 30,
    "part": false
  },
  {
    "no": "3.6",
    "title": "Offers",
    "page": 31,
    "part": false
  },
  {
    "no": "3.7",
    "title": "Recording an offer",
    "page": 32,
    "part": false
  },
  {
    "no": "3.8",
    "title": "Deals",
    "page": 33,
    "part": false
  },
  {
    "no": "3.9",
    "title": "Commission",
    "page": 34,
    "part": false
  },
  {
    "no": "3.10",
    "title": "Revenue",
    "page": 35,
    "part": false
  },
  {
    "no": "3.11",
    "title": "Documents: permits, cards and licences",
    "page": 36,
    "part": false
  },
  {
    "no": "04",
    "title": "Running the brokerage",
    "page": 37,
    "part": true
  },
  {
    "no": "4.1",
    "title": "Reports",
    "page": 38,
    "part": false
  },
  {
    "no": "4.2",
    "title": "Where your enquiries come from",
    "page": 39,
    "part": false
  },
  {
    "no": "4.3",
    "title": "What the assistant did",
    "page": 40,
    "part": false
  },
  {
    "no": "4.4",
    "title": "Team",
    "page": 41,
    "part": false
  },
  {
    "no": "4.5",
    "title": "Compliance (for the compliance officer)",
    "page": 42,
    "part": false
  },
  {
    "no": "05",
    "title": "Settings",
    "page": 43,
    "part": true
  },
  {
    "no": "5.1",
    "title": "Settings: the assistant's brake, calendar and listing feed",
    "page": 44,
    "part": false
  },
  {
    "no": "5.2",
    "title": "How the assistant's drafts are received",
    "page": 45,
    "part": false
  },
  {
    "no": "5.3",
    "title": "The assistant: questions, tone and automatic replies",
    "page": 46,
    "part": false
  },
  {
    "no": "5.4",
    "title": "Channels",
    "page": 47,
    "part": false
  },
  {
    "no": "5.5",
    "title": "Lead routing",
    "page": 48,
    "part": false
  },
  {
    "no": "5.6",
    "title": "Working hours",
    "page": 49,
    "part": false
  },
  {
    "no": "5.7",
    "title": "Nurture plans",
    "page": 50,
    "part": false
  },
  {
    "no": "5.8",
    "title": "Commission plans",
    "page": 51,
    "part": false
  },
  {
    "no": "5.9",
    "title": "Email",
    "page": 52,
    "part": false
  },
  {
    "no": "5.10",
    "title": "Import your history",
    "page": 53,
    "part": false
  },
  {
    "no": "5.11",
    "title": "Security and two-step sign-in",
    "page": 54,
    "part": false
  },
  {
    "no": "5.12",
    "title": "Support access",
    "page": 55,
    "part": false
  },
  {
    "no": "5.13",
    "title": "Privacy requests",
    "page": 56,
    "part": false
  },
  {
    "no": "5.14",
    "title": "Billing and invoices",
    "page": 57,
    "part": false
  },
  {
    "no": "06",
    "title": "On your phone",
    "page": 58,
    "part": true
  },
  {
    "no": "6.1",
    "title": "Using PotatoFarm.io on your phone",
    "page": 59,
    "part": false
  },
  {
    "no": "07",
    "title": "Routines and reference",
    "page": 60,
    "part": true
  },
  {
    "no": "7.1",
    "title": "Routines by role",
    "page": 61,
    "part": false
  },
  {
    "no": "7.2",
    "title": "When something looks wrong",
    "page": 62,
    "part": false
  },
  {
    "no": "7.3",
    "title": "Words we use",
    "page": 63,
    "part": false
  }
];
