import { View, Text, StyleSheet } from "react-native";
import Svg, { Path, Ellipse, Defs, LinearGradient, Stop, ClipPath, G } from "react-native-svg";
import { t } from "@/lib/theme";

/**
 * The lockup.
 *
 * One mark, drawn from the same geometry as `03-brand/logo/mark.py`.
 * The coordinates are duplicated here because React Native cannot
 * import an SVG file — not because there are two marks.
 *
 * ## Everything below the marker is generated. Do not edit it.
 *
 * This file is why the marker exists. It sat outside `mark.py --apply`'s
 * reach for three generations of artwork, because the propagator looks
 * for inline SVG and this renders `react-native-svg` components against
 * theme tokens. What that produced, all in one file: the body path of
 * the *third* artwork, an orphan string statement left dangling after
 * the `;` of the second, eye coordinates from the flat version, and
 * five doc comments in a row contradicting each other about whether the
 * eyes were capsules, speckles, or ovals.
 *
 * `palette.py` eventually caught it by the colours. Nothing caught the
 * geometry, because nothing was looking — the mobile app does not
 * build, so no screenshot and no type-check would ever have shown it.
 * **A stale mark in a file nobody compiles is still a second logo,
 * waiting to be shipped the day somebody fixes the build.**
 *
 * So `--apply` now rewrites the block between the markers, and the only
 * place to change any of it is `mark.py`.
 *
 * The `.io` sits inside the same `Text` node as the name so the two
 * kern against each other. On the web this had to be forced — a flex
 * container made them separate boxes and the browser drew a gap.
 */

/* MARK:BEGIN — generated by 03-brand/logo/mark.py --apply */

const BODY =
  "M27.6,3.0 C34.6,3.0 40.6,6.6 44.0,11.6 C46.6,17.2 48.8,23.6 50.8,29.8 C53.0,35.6 55.4,40.6 54.6,45.8 C53.4,53.0 47.2,58.6 39.8,60.5 C32.8,62.2 25.4,61.6 19.8,58.6 C13.4,55.2 9.4,49.0 8.9,42.0 C8.4,35.0 10.2,28.0 12.4,21.6 C14.6,15.2 17.0,8.0 21.4,5.2 C23.2,4.0 25.0,3.0 27.6,3.0 Z";

/** cx, cy, rx, ry. */
const EYES: [number, number, number, number][] = [
  [26.2, 31.4, 3.1, 4.4], [40.4, 31.4, 3.1, 4.4],
];

/** d, opacity — the mouth, the cheek line and two surface dashes. */
const CREASES: [string, number][] = [
  ["M21.9,50.4 Q27.0,46.9 29.3,52.6 Q26.3,49.3 21.9,50.4 Z", 0.9],
  ["M40.2,47.4 Q43.1,39.4 51.6,40.2 Q44.8,42.1 40.2,47.4 Z", 0.72],
  ["M26.0,11.7 Q28.9,8.1 32.9,10.4 Q29.2,10.0 26.0,11.7 Z", 0.85],
  ["M16.8,38.6 Q19.6,36.7 22.0,39.1 Q19.5,38.1 16.8,38.6 Z", 0.8],
];

/** cx, cy, rx, ry, opacity. */
const DOTS: [number, number, number, number, number][] = [
  [44.7, 17.6, 0.75, 0.95, 0.7],
  [47.6, 51.1, 0.85, 1.05, 0.5],
];
/* MARK:END */

export function Wordmark({ size = 17 }: { size?: number }) {
  // The mark is sized to the wordmark's cap height, not to a round
  // number — a mark that is 28px beside 17px type looks like two things
  // that arrived separately.
  const mark = Math.round(size * 1.65);
  return (
    <View style={s.row}>
      <Svg width={mark} height={mark} viewBox="0 0 64 64" style={s.mark}>
        <Defs>
          <LinearGradient id="body" x1="18%" y1="6%" x2="88%" y2="96%">
            <Stop offset="0" stopColor={t.markBodyHi} />
            <Stop offset="0.42" stopColor={t.markBody} />
            <Stop offset="0.72" stopColor={t.markBodyWarm} />
            <Stop offset="1" stopColor={t.markBodyLow} />
          </LinearGradient>
          <LinearGradient id="rim" x1="18%" y1="6%" x2="88%" y2="96%">
            <Stop offset="0" stopColor={t.markRim} />
            <Stop offset="1" stopColor={t.markRimLow} />
          </LinearGradient>
          <ClipPath id="body-clip">
            <Path d={BODY} />
          </ClipPath>
        </Defs>

        <Path d={BODY} fill="url(#body)" stroke="url(#rim)" strokeWidth={1.15}
              strokeLinejoin="round" />

        {/* The shading lobe. No blur: `react-native-svg` supports
            filters unevenly across platforms and a filter that silently
            does nothing on one of them is worse than none, so the lobe
            is drawn soft-edged by opacity alone and clipped to the
            body. */}
        <G clipPath="url(#body-clip)">
          <Ellipse cx={46} cy={52} rx={22} ry={18} fill={t.markShade} opacity={0.28} />
        </G>

        {EYES.map(([cx, cy, rx, ry], i) => (
          <Ellipse key={i} cx={cx} cy={cy} rx={rx} ry={ry} fill={t.markEye} />
        ))}
        {CREASES.map(([d, o], i) => (
          <Path key={i} d={d} fill={t.markCrease} opacity={o} />
        ))}
        {DOTS.map(([cx, cy, rx, ry, o], i) => (
          <Ellipse key={i} cx={cx} cy={cy} rx={rx} ry={ry} fill={t.markCrease} opacity={o} />
        ))}
      </Svg>
      <Text style={[s.name, { fontSize: size }]}>
        PotatoFarm<Text style={s.tld}>.io</Text>
      </Text>
    </View>
  );
}

const s = StyleSheet.create({
  row: { flexDirection: "row", alignItems: "center" },
  mark: { marginRight: 9 },
  name: { color: t.brandNavy, fontWeight: "600", letterSpacing: -0.2 },
  /** The .io takes the brand orange, the same value as the web's. */
  tld: { color: t.tld, fontWeight: "500" },
});
