"""Put the manual into the CRM: every page as an image the in-app reader
shows (phones cannot page through an embedded PDF — iPhone shows page one
and stops), the PDF itself for download, and the contents as a module.

python publish.py <manual.pdf> <pages2.json>
"""
import json, os, shutil, sys
import pypdfium2 as pdfium
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from content import PARTS, S
APP = os.path.abspath(f"{HERE}/../../02-the-project/app")
EDITION = "e2"
pdf_path, pages_json = sys.argv[1], sys.argv[2]
pages = json.load(open(pages_json))
# Outside public/: served only to signed-in people, by api/manual/[...path].
out = f"{APP}/manual-assets/{EDITION}"
shutil.rmtree(out, ignore_errors=True); os.makedirs(out)
pdf = pdfium.PdfDocument(pdf_path)
for i in range(len(pdf)):
    img = pdf[i].render(scale=1240 / pdf[i].get_width()).to_pil().convert("RGB")
    img.save(f"{out}/page-{i + 1:02d}.webp", "WEBP", quality=80, method=6)
shutil.copy(pdf_path, f"{APP}/manual-assets/PotatoFarm-Training-Manual.pdf")

num, rows = {}, []
for pi, (pid, ptitle, _) in enumerate(PARTS, 1):
    rows.append({"no": f"{pi:02d}", "title": ptitle, "page": pages.get("part-" + pid), "part": True})
    k = 0
    for s in S:
        if s["part"] == pid:
            k += 1
            rows.append({"no": f"{pi}.{k}", "title": s["title"], "page": pages.get(s["id"]), "part": False})
    if pid == "ref":
        for k, (rid, t) in enumerate([("routines", "Routines by role"), ("trouble", "When something looks wrong"), ("glossary", "Words we use")], 1):
            rows.append({"no": f"{pi}.{k}", "title": t, "page": pages.get(rid), "part": False})
rows.insert(0, {"no": "", "title": "Who does what", "page": pages.get("roles"), "part": False})
ts = (
    "// Generated by 05-documents/training-manual/publish.py — do not edit.\n"
    "// Rebuild the manual, then run it again; the reader follows.\n\n"
    f"export const EDITION = {json.dumps(EDITION)};\n"
    f"export const PAGE_COUNT = {len(pdf)};\n"
    "export const PDF_URL = \"/api/manual/pdf\";\n"
    f"export const PDF_BYTES = {os.path.getsize(pdf_path)};\n\n"
    "export type Entry = { no: string; title: string; page: number; part: boolean };\n"
    f"export const CONTENTS: Entry[] = {json.dumps(rows, indent=2)};\n"
)
os.makedirs(f"{APP}/src/app/(app)/manual", exist_ok=True)
open(f"{APP}/src/lib/manual.ts", "w").write(ts)
size = sum(os.path.getsize(f"{out}/{f}") for f in os.listdir(out))
print(f"{len(pdf)} pages, {size / 1e6:.1f} MB of page images, contents {len(rows)} entries")
