#!/usr/bin/env python3
"""
Move every surface to the current brand palette, in one pass.

The palette is declared in more than one place — it has to be, because
the website has no build step and the design-system pages have to open
without one either. `consistency.py` fails on drift between them, which
catches the problem after the fact; this is what makes them agree in the
first place.

**Why a script and not find-and-replace.** The last two palette changes
were done by hand and both went wrong in the same way: a bulk replace of
the accent also caught `--warning`, which was a *different* colour that
happened to share the hex, and a warning nobody can read stopped being a
warning. Twice. Here the mapping is explicit per token, the old value is
asserted present before anything is written, and `--warning` is named in
the map rather than swept up by it.

    python3 03-brand/repalette.py          # report what would change
    python3 03-brand/repalette.py --apply

Idempotent: running it twice changes nothing, which is how you can tell
it worked.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# old -> new, longest first so a substring never eats a longer match.
# Every entry is a deliberate decision, not a hue shift.
MAP = {
    # ---- OPTION 1 -----------------------------------------------------
    # The approved direction. Every value below is from the brief except
    # the four derived steps, which it asks for explicitly: "create
    # additional shades systematically from these colours rather than
    # introducing unrelated colours."
    #
    # The ground moves from warm cream to pure white and the accent from
    # #FF6B35 to #E86A2C. Both are real changes, and the second is worth
    # noting: #E86A2C is *closer to the supplied logo* than what shipped.
    # The `.io` in that artwork samples between #E66308 and #ED8037.

    # The brand orange and its derived steps, same hue throughout.
    "#FF6B35": "#E86A2C",   # accent, accent-type, the .io   3.22:1 on white
    "#E85A25": "#CF5A22",   # accent-hover — a fill state    4.09:1
    "#CC4E1D": "#B94E1F",   # accent-edge — the brief's Deep Potato Orange
    "#A84015": "#A0431B",   # accent-deep + danger + warning 6.34:1, small type

    # The ground. Cream to white, panel to the brief's warm grey.
    "#F4F3F0": "#FFFFFF",   # --ground
    "#EBEAE6": "#F5F3F0",   # --panel  (the brief's Warm Grey)

    # Ink. #1A1A1A to the brief's Deep Charcoal.
    "#1A1A1A": "#171717",   # --ink, --success, --on-accent  17.93:1
    # Not in the map, and deliberately: `--ink-2` (#4A4A4A, 8.86:1 on
    # white) and `--ink-3` (#6B6B6B) already *are* the brief's Medium
    # Grey and its darker partner. An identity mapping would also break
    # this script's own check, which asserts the old value is gone.

    # Rules. The brief's border, plus a stronger step it does not give
    # and WCAG 1.4.11 requires: a form control's boundary needs 3:1
    # against its background, and #E7E5E2 is 1.26:1. That is fine for a
    # hairline between rows and not fine for the edge of an input.
    "#E2E0DA": "#E7E5E2",   # --rule        1.26:1 — separators
    "#CFCCC4": "#918A82",   # --rule-strong 3.41:1 — control boundaries

    # The focus ring, written as rgb() channels rather than hex.
    "rgb(255 107 53": "rgb(232 106 44",
    "255, 107, 53": "232, 106, 44",
}


# Everything that declares a colour. The logo mark's own gradient is
# deliberately absent: it is artwork, it is generated by mark.py, and
# the `.io` in the lockups is covered by the accent mapping above.
TARGETS = [
    "02-the-project/app/src/styles/tokens.css",
    "02-the-project/app/src/styles/globals.css",
    # The lockup moved out of the shell into one component.
    "02-the-project/app/src/components/brand/logo.tsx",
    # Colour that lives outside a stylesheet, and every one of these was
    # missed by the last two palette moves because it is not CSS.
    "02-the-project/app/src/server/lib/mail.ts",      # inline-styled email
    "02-the-project/app/src/app/layout.tsx",          # themeColor
    "02-the-project/app/public/site.webmanifest",     # theme + background
    "02-the-project/website/site.webmanifest",
    "03-brand/logo/mark.py",                          # the .io, not the gradient
    "03-brand/logo/build.mjs",                        # the grounds it renders on
    "03-brand/logo/README.md",
    "03-brand/logo/PALETTE.md",
    "02-the-project/app/preview-mobile.html",
    "02-the-project/app/mobile/lib/theme.ts",
    "02-the-project/app/mobile/components/wordmark.tsx",
    "02-the-project/app/mobile/_check.py",
    "02-the-project/website/assets/site.css",
    "02-the-project/website/404.html",
    "02-the-project/website/demo.html",
    "02-the-project/website/guides.html",
    "02-the-project/website/index.html",
    "02-the-project/website/legal.html",
    "02-the-project/website/product.html",
    "02-the-project/website/security.html",
    "02-the-project/website/trakheesi-permits.html",
    "02-the-project/website/uae-aml-for-brokerages.html",
    "02-the-project/website/whatsapp-24-hour-window.html",
    "03-brand/design-system/dashboard-v4.html",
    "03-brand/design-system/homepage-v4.html",
    "03-brand/logo/lockup.svg",
    "03-brand/logo/lockup-stacked.svg",
    "03-brand/logo/lockup-stacked-onbg.svg",
]

apply = "--apply" in sys.argv
changed, total = [], 0

for rel in TARGETS:
    p = ROOT / rel
    if not p.exists():
        print(f"  MISSING  {rel}")
        continue
    src = p.read_text()
    out = src
    hits = 0
    for old, new in sorted(MAP.items(), key=lambda kv: -len(kv[0])):
        for form in {old, old.lower(), old.upper()}:
            n = out.count(form)
            if n:
                out = out.replace(form, new if form == old else
                                  (new.lower() if form == old.lower() else new.upper()))
                hits += n
    if hits:
        total += hits
        changed.append((rel, hits))
        if apply:
            p.write_text(out)

for rel, n in changed:
    print(f"  {'wrote ' if apply else 'would'}  {rel:<58} {n}")

print(f"\n{total} replacement(s) across {len(changed)} file(s)"
      f"{'' if apply else '  — run with --apply'}")

# A palette change that leaves one stale hex behind is the whole problem
# this script exists to stop, so look for survivors rather than trusting
# the count above.
if apply:
    stale = []
    for rel in TARGETS:
        p = ROOT / rel
        if not p.exists():
            continue
        text = p.read_text()
        for old in MAP:
            if not old.startswith("#"):
                continue
            for m in re.finditer(re.escape(old), text, re.I):
                line = text[:m.start()].count("\n") + 1
                stale.append(f"{rel}:{line}  {old}")
    if stale:
        print("\nSTALE VALUES REMAIN:")
        for s in stale:
            print(f"  x {s}")
        sys.exit(1)
    print("No old value survives in any target.")
