#!/usr/bin/env python3
"""
Move every surface to the current brand palette, in one pass.

The palette is declared in more than one place — it has to be, because
the website has no build step and the design-system pages have to open
without one either. `consistency.py` fails on drift between them, which
catches the problem after the fact; this is what makes them agree in the
first place.

**Why a script and not find-and-replace.** The last two palette changes
were done by hand and both went wrong in the same way: a bulk replace of
the accent also caught `--warning`, which was a *different* colour that
happened to share the hex, and a warning nobody can read stopped being a
warning. Twice. Here the mapping is explicit per token, the old value is
asserted present before anything is written, and `--warning` is named in
the map rather than swept up by it.

    python3 03-brand/repalette.py          # report what would change
    python3 03-brand/repalette.py --apply

Idempotent: running it twice changes nothing, which is how you can tell
it worked.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# old -> new, longest first so a substring never eats a longer match.
# Every entry is a deliberate decision, not a hue shift.
MAP = {
    # The brand orange, and its two derived steps in the same hue.
    "#FF6600": "#FF6B35",   # accent, accent-type, the .io          2.56:1
    "#E55C00": "#E85A25",   # accent-hover — a fill state           3.20:1
    "#CC5200": "#CC4E1D",   # accent-edge, the hairline on a fill   3.73:1 panel
    "#A84900": "#A84015",   # accent-deep + warning — small type    5.55:1

    # State is no longer a hue. See the note in tokens.css: all 32 uses
    # already carried the word, and the two that did not are now filled
    # versus hollow dots.
    "#1F7A4C": "#1A1A1A",   # success -> ink
    "#B3261E": "#A84015",   # danger  -> the readable accent step

    # The focus ring, written as rgb() channels rather than hex.
    "rgb(255 102 0": "rgb(255 107 53",
    "255, 102, 0": "255, 107, 53",
}

# Everything that declares a colour. The logo mark's own gradient is
# deliberately absent: it is artwork, it is generated by mark.py, and
# the `.io` in the lockups is covered by the accent mapping above.
TARGETS = [
    "02-the-project/app/src/styles/tokens.css",
    "02-the-project/app/src/styles/globals.css",
    "02-the-project/app/src/components/layout/shell.tsx",
    "02-the-project/app/preview-mobile.html",
    "02-the-project/app/mobile/lib/theme.ts",
    "02-the-project/app/mobile/components/wordmark.tsx",
    "02-the-project/app/mobile/_check.py",
    "02-the-project/website/assets/site.css",
    "03-brand/design-system/dashboard-v4.html",
    "03-brand/design-system/homepage-v4.html",
    "03-brand/logo/lockup.svg",
    "03-brand/logo/lockup-stacked.svg",
    "03-brand/logo/lockup-stacked-onbg.svg",
]

apply = "--apply" in sys.argv
changed, total = [], 0

for rel in TARGETS:
    p = ROOT / rel
    if not p.exists():
        print(f"  MISSING  {rel}")
        continue
    src = p.read_text()
    out = src
    hits = 0
    for old, new in sorted(MAP.items(), key=lambda kv: -len(kv[0])):
        for form in {old, old.lower(), old.upper()}:
            n = out.count(form)
            if n:
                out = out.replace(form, new if form == old else
                                  (new.lower() if form == old.lower() else new.upper()))
                hits += n
    if hits:
        total += hits
        changed.append((rel, hits))
        if apply:
            p.write_text(out)

for rel, n in changed:
    print(f"  {'wrote ' if apply else 'would'}  {rel:<58} {n}")

print(f"\n{total} replacement(s) across {len(changed)} file(s)"
      f"{'' if apply else '  — run with --apply'}")

# A palette change that leaves one stale hex behind is the whole problem
# this script exists to stop, so look for survivors rather than trusting
# the count above.
if apply:
    stale = []
    for rel in TARGETS:
        p = ROOT / rel
        if not p.exists():
            continue
        text = p.read_text()
        for old in MAP:
            if not old.startswith("#"):
                continue
            for m in re.finditer(re.escape(old), text, re.I):
                line = text[:m.start()].count("\n") + 1
                stale.append(f"{rel}:{line}  {old}")
    if stale:
        print("\nSTALE VALUES REMAIN:")
        for s in stale:
            print(f"  x {s}")
        sys.exit(1)
    print("No old value survives in any target.")
